---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app navidrome
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: navidrome
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      enableServiceLinks: false
    controllers:
      navidrome:
        containers:
          app:
            image:
              repository: ghcr.io/navidrome/navidrome
              tag: 0.63.2@sha256:9012939114fbb1bb641b81cf96dec5ded15f0aafefe8d47a511d7cb919658e40
            env:
              TZ: "Europe/Paris"
              ND_DATAFOLDER: /config
              ND_ENABLEGRAVATAR: "true"
              ND_LOGLEVEL: info
              ND_MUSICFOLDER: /mnt/vol1/music/Artistes
              ND_PORT: &port 8080
              ND_PROMETHEUS_ENABLED: "true"
              ND_REVERSEPROXYUSERHEADER: Remote-User
              ND_REVERSEPROXYWHITELIST: 0.0.0.0/0
              ND_SCANSCHEDULE: "@every 1h"
              ND_SESSIONTIMEOUT: 24h
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                memory: 750Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 200"]
        hostnames: ["{{ .Release.Name }}.xpander.ovh"]
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /config
      music:
        type: nfs
        server: 192.168.9.10
        path: /mnt/vol1/music
        globalMounts:
          - path: /mnt/vol1/music
            readOnly: true
