---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.config.k8s.io/kustomization_v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
components:
  - ../../components/alerts
resources:
  - ./namespace.yaml
  - ./amd-device-plugin/ks.yaml
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./descheduler/ks.yaml
  - ./generic-device-plugin/ks.yaml
  - ./k8tz/ks.yaml
  - ./metrics-server/ks.yaml
  - ./multus/ks.yaml
  - ./reloader/ks.yaml
  - ./snapshot-controller/ks.yaml
  - ./spegel/ks.yaml
