---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/k8s.cni.cncf.io/networkattachmentdefinition_v1.json
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: iot
spec:
  config: |-
    {
      "cniVersion": "1.1.0",
      "name": "iot",
      "plugins": [
        {
          "type": "macvlan",
          "master": "eth0",
          "mode": "bridge",
          "vlan": 12,
          "ipam": {
            "type": "static",
            "addresses": [
              {"address": "192.168.12.10/24","gateway": "192.168.12.1"}
            "routes": [
              {"dst": " 192.168.12.0/22", "gw": "192.168.12.1"}
            ]
          }
        }
      ]
    }
