---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flaresolverr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: flaresolverr
  values:
    controllers:
      flaresolverr:
        containers:
          app:
            image:
              repository: ghcr.io/flaresolverr/flaresolverr
              tag: v3.5.2@sha256:c80ae007ce2ccdcd217a12426e4f039ef763ff90738c808d38810c3e59323767
            resources:
              requests:
                cpu: 10m
                memory: 150Mi
              limits:
                memory: 500Mi
    service:
      app:
        controller: flaresolverr
        ports:
          http:
            port: 8191
