---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: donetick-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: donetick-secrets
    creationPolicy: Owner
    template:
      data:
        DT_JWT_SECRET: "{{ .DONETICK_JWT_SECRET }}"
  dataFrom:
  - extract:
      key: donetick
