{
 "title": "New dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Backup status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "resticprofile_backup_status", "legendFormat": "{{profile}}" }
   ]
  },
  {
   "title": "Backup duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "resticprofile_backup_duration_seconds",
     "legendFormat": "{{profile}}"
    }
   ]
  },
  {
   "title": "Files processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "resticprofile_backup_files_processed",
     "legendFormat": "{{profile}}"
    }
   ]
  },
  {
   "title": "Processed bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "resticprofile_backup_processed_bytes",
     "legendFormat": "{{profile}}"
    }
   ]
  }
 ]
}