---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-gateway
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: k8s-gateway
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: k8s-gateway
    domain: "${SECRET_EXTERNAL_DOMAIN}"
    ttl: 1
    service:
      type: LoadBalancer
      port: 53
      annotations:
        io.cilium/lb-ipam-ips: ${CLUSTER_LB_K8SGATEWAY}
      externalTrafficPolicy: Cluster
    watchedResources: [HTTPRoute, Service]
