---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich-microservices
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: immich
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: immich
  values:
    controllers:
      immich-microservices:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v2.7.5@sha256:c15bff75068effb03f4355997d03dc7e0fc58720c2b54ad6f7f10d1bc57efaa5
            env:
              TZ: ${TIMEZONE}
              IMMICH_WORKERS_EXCLUDE: api
            envFrom:
              - configMapRef:
                  name: immich-configmap
              - secretRef:
                  name: immich-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 512Mi
                gpu.intel.com/i915: 1
              limits:
                memory: 8000Mi
                gpu.intel.com/i915: 1
    defaultPodOptions:
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      library:
        enabled: true
        type: nfs
        server: 192.168.9.10
        path: /mnt/vol1/apps/immich
        globalMounts:
          - path: /data
      external:
        enabled: true
        type: nfs
        server: 192.168.9.10
        path: /mnt/vol1/photo/Export
        globalMounts:
          - path: /external_libs
