---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xpander-ovh
spec:
  dnsNames:
    - xpander.ovh
    - "*.xpander.ovh"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: xpander-ovh-tls
  usages:
    - digital signature
