---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: etcd-backup
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: etcd-backup-s3
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .ACCESS_KEY }}"
        AWS_SECRET_ACCESS_KEY: "{{ .SECRET_KEY }}"
        AGE_X25519_PUBLIC_KEY: "{{ .AGE_PUBLIC_KEY }}"
  dataFrom:
    - extract:
        key: etcd-backup
