---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-secret
    template:
      data:
        # App
        JWT_SECRET: "{{ .IMMICH__JWT_SECRET }}"
        # Database
        DB_HOSTNAME: &dbhost "immich-database.default.svc.cluster.local."
        DB_PORT: "5432"
        DB_USERNAME: &dbuser "{{ .IMMICH__POSTGRES_USER }}"
        DB_PASSWORD: &dbpass "{{ .IMMICH__POSTGRES_PASSWORD }}"
        DB_DATABASE_NAME: immich
  dataFrom:
    - extract:
        key: immich
