---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich-database
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: immich
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
    controllers:
      primary:
        type: statefulset
        containers:
          postgresql:
            image:
              repository: ghcr.io/immich-app/postgres
              tag: 18-vectorchord0.5.3@sha256:b2f93fb4d9c1c0c720d6bf61e26f237f0aed12dcb4109dfb447ef7ae9dc209ce
            env:
              PGDATA: /var/lib/postgresql/data
            envFrom:
              - configMapRef:
                  name: immich-configmap
              - secretRef:
                  name: immich-secret
            resources:
              requests:
                cpu: 500m
                memory: 512Mi
              limits:
                cpu: 750m
                memory: 768Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
          # metrics:
          #   image:
          #     repository: quay.io/prometheuscommunity/postgres-exporter
          #     tag: v0.19.1@sha256:e96064f876226d94bb6ce48a4c4b3dd76edba91168ec1ab024e5c4b959310b0f
          #   env:
          #     DATA_SOURCE_URI: localhost:5432/postgres?sslmode=disable
          #     DATA_SOURCE_USER: immich
          #     DATA_SOURCE_PASS: ${SECRET_IMMICH_DB_PASSWORD}
          #   resources:
          #     requests:
          #       cpu: 100m
          #       memory: 128Mi
          #     limits:
          #       cpu: 150m
          #       memory: 192Mi
          #   probes:
          #     liveness:
          #       enabled: true
          #     readiness:
          #       enabled: true
        initContainers:
          init-postgres-permissions:
            image:
              repository: alpine
              tag: 3.23@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11
            command:
              - /bin/sh
              - -c
              - |
                chown -R 999:999 $PGDATA
                chmod 700 $PGDATA
            env:
              PGDATA: /var/lib/postgresql/data
            securityContext:
              runAsUser: 0
              runAsGroup: 0
          # # Init Container for Major PostgreSQL Upgrades, not needed permanently
          # pgautoupgrade:
          #   image:
          #     repository: ghcr.io/pumba98/pgautoupgrade-vchord
          #     tag: 17-debian-v0.3.0
          #   # securityContext:
          #   #   runAsUser: 0
          #   #   runAsGroup: 0
          #   env:
          #     PGAUTO_ONESHOT: yes
          #     POSTGRES_USER: immich
          #     POSTGRES_DB: immich
          #     PGDATA: /var/lib/postgresql/data
    service:
      primary:
        controller: primary
        ports:
          postgresql:
            port: 5432
      # metrics:
      #   controller: primary
      #   ports:
      #     metrics:
      #       port: 9187
    persistence:
      data:
        existingClaim: immich-database
        globalMounts:
          - path: /var/lib/postgresql/data
            subPath: data
    # serviceMonitor:
    #   main:
    #     enabled: true
    #     serviceName: immich-postgresql-metrics
    #     endpoints:
    #       - port: metrics
