---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sensy-one-zone-editor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sensy-one-zone-editor-secret
    template:
      engineVersion: v2
      data:
        HA_TOKEN: "{{ .SENSY_ONE_TOKEN }}"
        HA_URL: "https://home-assistant.{{ .SECRET_EXTERNAL_DOMAIN }}"
  dataFrom:
    - extract:
        key: generic
    - extract:
        key: home-assistant
