---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app opengist
spec:
  chartRef:
    kind: OCIRepository
    name: opengist
  interval: 1h
  values:
    controllers:
      opengist:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/thomiceli/opengist
              tag: 1.15.2@sha256:7edc91273ee7d10a17406da8a08c803158baaff984c39b789c1313473d068f21
            command: # double "$$" escape flux substitutions
              - ./opengist
            args:
              - --config
              - /config/config.yaml
            resources:
              requests:
                cpu: 100m
                memory: 52M
              limits:
                memory: 256M
            securityContext:
              allowPrivilegeEscalation: false
              # readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

    defaultPodOptions:
      securityContext:
        # runAsGroup: 65534
        # runAsUser: 65534
        # runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 6157
          # ssh:
          #   port: 2222
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 200"]
        hostnames: ["{{ .Release.Name }}.xpander.ovh"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      config:
        type: configMap
        name: opengist-configmap
        globalMounts:
          - subPath: config.yaml
            path: /config/config.yaml
        defaultMode: 0775
      data:
        existingClaim: *app
        globalMounts:
          - path: /config
