---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zeroclaw
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zeroclaw-secret
    template:
      engineVersion: v2
      data:
        BOT_APP_ID: "{{ .BOT_APP_ID }}"
        BOT_PRIVATE_KEY: "{{ .BOT_PRIVATE_KEY }}"
        OPENROUTER_API_KEY: "{{ .ZEROCLAW__OPENROUTER_API_KEY }}"
        TELEGRAM_BOT_TOKEN: "{{ .ZEROCLAW__TELEGRAM_BOT_TOKEN }}"
  dataFrom:
    - extract:
        key: feisar-bot-auricom-github
    - extract:
        key: zeroclaw
