{
 "title": "Homelab / Temperatures",
 "tags": [ "homelab" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "OPNsense - CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(node_cpu_temperature_celsius{app=\"opnsense\"})",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "k3s Nodes - CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg (node_hwmon_temp_celsius{chip=\"platform_coretemp_0\"}) by (chip,kubernetes_node) * ignoring(chip_name) group_left(chip_name) avg (node_hwmon_chip_names) by (chip,chip_name,kubernetes_node)",
     "legendFormat": "{{chip_name}}"
    }
   ]
  },
  {
   "title": "Datacenter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(hass_sensor_temperature_celsius{entity=~\"sensor.temperature_servers_temperature\"})",
     "legendFormat": "datacenter"
    }
   ]
  }
 ]
}