---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookorbit
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: bookorbit-secret
    creationPolicy: Owner
    template:
      data:
        JWT_SECRET: "{{ .BOOKORBIT_JWT_SECRET }}"
        SETUP_BOOTSTRAP_TOKEN: "{{ .BOOKORBIT_SETUP_BOOTSTRAP_TOKEN }}"
        EMAIL_ENCRYPTION_KEY: "{{ .BOOKORBIT_EMAIL_ENCRYPTION_KEY }}"
        MIGRATION_ENCRYPTION_KEY: "{{ .BOOKORBIT_MIGRATION_ENCRYPTION_KEY }}"
        BOOK_REQUEST_ENCRYPTION_KEY: "{{ .BOOKORBIT_BOOK_REQUEST_ENCRYPTION_KEY }}"
  dataFrom:
    - extract:
        key: bookorbit
