---
all:
  hosts:
    coreelec:
      ansible_host: coreelec.{{ internal_domain }}
      ansible_user: root
  children:
    truenas-instances:
      hosts:
        storage:
          ansible_host: storage.{{ internal_domain }}
          truenas_10gbe_interfaces:
            - enp2s0f0np0
            - enp2s0f1np1
        storage-remote:
          ansible_host: storage-remote.{{ internal_domain }}
          ansible_port: 35875
      vars:
        ansible_user: homelab
    unifios:
      hosts:
        ucgf:
          ansible_host: 192.168.16.1
          ansible_user: root
