---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app readeck
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: readeck
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      readeck:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: codeberg.org/readeck/readeck
              tag: 0.22.3@sha256:ed1c513f8e1d59b1d38fda324ac279eeb65afd0327907e498061ec9fd2f31c15
            env:
              TZ: "${TIMEZONE}"
              READECK_LOG_LEVEL: info
              READECK_DEV_MODE: "false"
              READECK_SERVER_HOST: 0.0.0.0
              READECK_SERVER_PORT: &port 8080
              READECK_SERVER_PREFIX: /
              READECK_USE_X_FORWARDED: "true"
              READECK_ALLOWED_HOSTS: &host "{{ .Release.Name }}.${SECRET_EXTERNAL_DOMAIN}"
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 2000Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 200"]
        hostnames: ["{{ .Release.Name }}.${SECRET_EXTERNAL_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /readeck
