---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app readeck
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: readeck
  values:
    controllers:
      readeck:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: codeberg.org/readeck/readeck
              tag: 0.23.4@sha256:fc34b2e9bc766422a4265dc253d1a3e95e0608ee08e86c7e3dda8773ec906fdc
            env:
              READECK_LOG_LEVEL: info
              READECK_DEV_MODE: "false"
              READECK_SERVER_HOST: 0.0.0.0
              READECK_SERVER_PORT: &port 8080
              READECK_SERVER_PREFIX: /
              READECK_USE_X_FORWARDED: "true"
              READECK_ALLOWED_HOSTS: &host "{{ .Release.Name }}.xpander.ovh"
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 2000Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["{{ .Release.Name }}.xpander.ovh"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /readeck
