---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app renamarr
  namespace: default
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: renamarr
  values:
    externalSecrets:
      renamarr:
        secretStoreRef:
          kind: ClusterSecretStore
          name: onepassword-connect
        target:
          template:
            engineVersion: v2
            data:
              RADARR_API_KEY: "{{ .RADARR__API_KEY }}"
              SONARR_API_KEY: "{{ .SONARR__API_KEY }}"
        dataFrom:
          - extract:
              key: radarr
              property: RADARR__API_KEY
          - extract:
              key: sonarr
              property: SONARR__API_KEY
    controllers:
      renamarr:
        type: cronjob
        cronjob:
          concurrencyPolicy: Forbid
          schedule: 0 */12 * * * # Every 12 hours
        containers:
          app:
            image:
              repository: ghcr.io/hollanbm/renamarr
              tag: 4.0.0@sha256:27cf6cfe73a4d370527deaf26b4a4ebe390bd5008ac0a009f991358b26cbbf84
            envFrom:
              - externalSecretRef:
                  identifier: renamarr
            resources:
              requests:
                cpu: 20m
                memory: 256M
    service:
      app:
        controller: *app
        enabled: false
    persistence:
      scripts:
        type: configMap
        name: renamarr-configmap
        defaultMode: 0444 # trunk-ignore(yamllint/octal-values)
        globalMounts:
          - path: /config/config.yml
            subPath: config.yml
            readOnly: true
