{
 "title": "Home-Assistant",
 "tags": [ "home-assistant" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Home",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(hass_sensor_temperature_celsius{entity=\"sensor.temperature_living_room_temperature\"})",
     "legendFormat": "Salon"
    },
    {
     "expr": "sum(hass_sensor_temperature_celsius{entity=~\"sensor.temperature_bedroom_temperature\"})",
     "legendFormat": "Chambre 1"
    },
    {
     "expr": "sum(hass_sensor_temperature_celsius{entity=~\"sensor.temperature_office_temperature\"})",
     "legendFormat": "Bureau"
    }
   ]
  },
  {
   "title": "Computers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(hass_sensor_power_w{entity=\"sensor.servers_plug_switch_electricity_power\"})",
     "legendFormat": "Servers"
    },
    {
     "expr": "sum(hass_sensor_power_w{entity=\"sensor.bureau_plug_switch_electricity_power\"})",
     "legendFormat": "claude-fixe"
    }
   ]
  },
  {
   "title": "Home Cinema",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "hass_sensor_power_w{entity=~\"sensor.power_plug_avr_power\"}",
     "legendFormat": "Ampli"
    },
    {
     "expr": "hass_sensor_power_w{entity=~\"sensor.power_plug_projector_power\"}",
     "legendFormat": "Vidéoprojecteur"
    },
    {
     "expr": "hass_sensor_power_w{entity=~\"sensor.power_plug_subwoofer_power\"}",
     "legendFormat": "Caisson de basses"
    }
   ]
  }
 ]
}