{
 "title": "Homelab / Temperatures",
 "tags": [ "homelab" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "OPNsense - CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by (app) (node_cpu_temperature_celsius{app=\"opnsense\"})",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "k3s Nodes - CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by (kubernetes_node) (\r\n  node_hwmon_temp_celsius{chip=\"platform_coretemp_0\"}\r\n )",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Datacenter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(hass_sensor_temperature_celsius{entity=~\"sensor.temperature_servers_temperature\"})",
     "legendFormat": "datacenter"
    }
   ]
  }
 ]
}