---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zeroclaw
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zeroclaw-secret
    template:
      engineVersion: v2
      data:
        ZEROCLAW_API_KEY: "{{ .ZEROCLAW_API_KEY }}"
  dataFrom:
    - extract:
        key: zeroclaw
