---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: komf
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: komf-secret
  dataFrom:
    - extract:
        # KOMF_KOMGA_USER, KOMF_KOMGA_PASSWORD
        key: komf
