---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
spec:
  chartRef:
    kind: OCIRepository
    name: gatus
  interval: 1h
  values:
    externalSecrets:
      gatus:
        secretStoreRef:
          kind: ClusterSecretStore
          name: onepassword-connect
        target:
          template:
            data:
              CUSTOM_PUSHOVER_APP_TOKEN: "{{ .PUSHOVER_API_TOKEN }}"
              CUSTOM_PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        dataFrom:
          - extract:
              key: gatus
          - extract:
              key: pushover
    defaultPodOptions:
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
    controllers:
      gatus:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          gatus-sidecar:
            image:
              repository: ghcr.io/home-operations/gatus-sidecar
              tag: 0.5.3@sha256:b52ae9161639c7453308096aa8f5095d540196d097f5e3c681465737f22e8e76
            args:
              - --auto-httproute
              - --enable-httproute
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 128Mi
            restartPolicy: Always
        containers:
          app:
            image:
              repository: ghcr.io/twin/gatus
              tag: v5.37.0@sha256:094eb186e55235db367e90e9d56140e5897b7044c41de23cde4cc18e6da1242e
            env:
              GATUS_DELAY_START_SECONDS: 5
              GATUS_CONFIG_PATH: /config
              GATUS_WEB_PORT: &port 80
              TZ: Europe/Paris
            envFrom:
              - externalSecretRef:
                  identifier: gatus
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
        serviceAccount:
          identifier: gatus
    persistence:
      config:
        type: emptyDir
      config-file:
        type: configMap
        name: gatus-configmap
        globalMounts:
          - path: /config/static/config.yaml
            subPath: config.yaml
            readOnly: true
    rbac:
      roles:
        gatus:
          type: ClusterRole
          rules:
            - apiGroups: ["gateway.networking.k8s.io"]
              resources: ["gateways", "httproutes"]
              verbs: ["get", "watch", "list"]
      bindings:
        gatus:
          type: ClusterRoleBinding
          roleRef:
            identifier: gatus
          subjects:
            - identifier: gatus
    route:
      app:
        annotations:
          gatus.home-operations.com/enabled: "false"
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        hostnames:
          - status.xpander.ovh
    service:
      app:
        controller: gatus
        ports:
          http:
            port: *port
    serviceAccount:
      gatus: {}
    serviceMonitor:
      app:
        endpoints:
          - port: http
