---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xpander-ovh-unifi
spec:
  secretName: xpander-ovh-unifi
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "unifi.xpander.ovh"
  dnsNames:
    - unifi.xpander.ovh
  keystores:
    jks:
      create: true
      alias: unifi
      password: aircontrolenterprise
