{
 "title": "Homelab / Temperatures",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "OPNsense - CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg by (app) (node_cpu_temperature_celsius{app=\"opnsense\"})",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "k3s Nodes - CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg by (kubernetes_node) (\r\n  node_hwmon_temp_celsius{chip=\"platform_coretemp_0\"}\r\n )",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Datacenter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "hass_temperature_c{entity=~\"sensor.temperature_servers_temperature\"}",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}