{
 "title": "Terra",
 "tags": [
  "crypto",
  "terra"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "pair", "query": "bluna-luna,meth-beth,beth-ust" }
  ]
 },
 "panels": [
  { "title": "${pair}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pair" },
  {
   "title": "APR",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "terra_pool_pairs_apr{slug=\"${pair}\"}"
    }
   ]
  },
  {
   "title": "Liquidity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "terra_pool_pairs_liquidity{slug=\"${pair}\"}"
    }
   ]
  },
  {
   "title": "APR",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "terra_pool_pairs_apr{slug=\"${pair}\"}",
     "legendFormat": "APR"
    }
   ]
  },
  {
   "title": "Volume (24h)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "terra_pool_pairs_vol_24h{slug=\"${pair}\"}"
    }
   ]
  },
  {
   "title": "Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "terra_pool_pairs_liquidity{slug=\"${pair}\"}",
     "legendFormat": "Liquidity"
    },
    {
     "expr": "terra_pool_pairs_vol_24h{slug=\"${pair}\"}",
     "legendFormat": "Volume (24h)"
    }
   ]
  }
 ]
}