---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app lldap
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: lldap
  values:
    externalSecrets:
      lldap:
        secretStoreRef:
          kind: ClusterSecretStore
          name: onepassword-connect
        target:
          template:
            engineVersion: v2
            data:
              LLDAP_JWT_SECRET: "{{ .LLDAP_JWT_SECRET }}"
              LLDAP_KEY_SEED: "{{ .LLDAP_KEY_SEED }}"
              LLDAP_LDAP_USER_PASS: "{{ .password }}"
              LLDAP_LLDAP_USER_DN: "{{ .username }}"
              LLDAP_LDAP_USER_EMAIL: "{{ .LLDAP_LDAP_USER_EMAIL }}"
              LLDAP_SERVER_KEY_SEED: "{{ .LLDAP_SERVER_KEY_SEED }}"
        dataFrom:
          - extract:
              key: lldap
    controllers:
      lldap:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/lldap/lldap
              tag: v0.6.3@sha256:2a8454b668c1aba7157e832eab0e242e1e7eb5fb7591d7e7774ba05286511ca8
            env:
              LLDAP_HTTP_PORT: &port 8080
              LLDAP_HTTP_URL: https://lldap.xpander.ovh
              LLDAP_LDAP_PORT: &ldapPort 5389
              LLDAP_LDAP_BASE_DN: dc=home,dc=arpa
            envFrom:
              - externalSecretRef:
                  identifier: lldap
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
              limits:
                memory: 500Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
          ldap:
            enabled: true
            port: *ldapPort
    route:
      app:
        hostnames: ["{{ .Release.Name }}.xpander.ovh"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /data
