---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unpoller
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: unpoller
  values:
    externalSecrets:
      unpoller:
        secretStoreRef:
          kind: ClusterSecretStore
          name: onepassword-connect
        target:
          template:
            engineVersion: v2
            data:
              UP_UNIFI_DEFAULT_API_KEY: "{{ .UNPOLLER_UNIFI_API_KEY }}"
        dataFrom:
          - extract:
              key: unifi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
    controllers:
      unpoller:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/unpoller/unpoller
              tag: v5.2.8@sha256:ca82e584b9bb3c8d2f9998adb429ab9f9bbb8840388ba10f2c62f07bd31ea0e9
            env:
              UP_UNIFI_DEFAULT_URL: https://192.168.30.1
              UP_PROMETHEUS_HTTP_LISTEN: 0.0.0.0:80
              UP_INFLUXDB_DISABLE: true
            envFrom:
              - externalSecretRef:
                  identifier: unpoller
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    service:
      app:
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        serviceName: "{{ .Release.Name }}"
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 2m # Unifi API only polls at 2m intervals
            scrapeTimeout: 10s
