---
originRequest:
  originServerName: external.xpander.ovh

ingress:
  - hostname: "xpander.ovh"
    service: &svc https://envoy-network-external-b1d9befd.network.svc.cluster.local:443
  - hostname: "*.xpander.ovh"
    service: *svc
  - service: http_status:404
