---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: elegoo-cc2-webui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: elegoo-cc2-webui-secret
    template:
      engineVersion: v2
      data:
        ACCESS_CODE: '{{.access_code}}'
  dataFrom:
    - extract:
        key: elegoo-cc2-webui
