---
- name: verify | wait for blocky to be ready
  ansible.builtin.wait_for:
    port: "{{ unifios_blocky_dns_port }}"
    host: 127.0.0.1
    timeout: 30

- name: verify | test blocky directly
  ansible.builtin.command: "dig @127.0.0.1 -p {{ unifios_blocky_dns_port }} google.com"
  changed_when: false

- name: verify | test dnsmasq forwarding
  ansible.builtin.command: "dig @127.0.0.1 google.com"
  changed_when: false

- name: verify | test ad blocking
  ansible.builtin.command: "dig @127.0.0.1 googleads.g.doubleclick.net"
  changed_when: false
