---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-sync-secret
    template:
      data:
        API_KEY: "{{ .IMMICH__SYNC_API_KEY }}"
  dataFrom:
    - extract:
        key: immich
