---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich-sync
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: immich
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: immich
  values:
    controllers:
      immich-sync:
        type: cronjob
        cronjob:
          concurrencyPolicy: Forbid
          schedule: "45 7 * * *"
        containers:
          app:
            image:
              repository: ghcr.io/salvoxia/immich-folder-album-creator
              tag: 0.25.2@sha256:79b82f9818ded34c8dcfc5df0502126fdaff698b94ddad4b20ac1f0c3a7dcba2
            command:
              - python3
              - /script/immich_auto_album.py
            args:
              - --api-key-type=literal
              - --unattended
              - --album-order=asc
              - --album-separator=""
              - --share-with=Hélène=viewer
              - --album-name-post-regex='[\d]+_[\d]+_'
              - --album-name-post-regex="'_' ' '"
              - /external_libs
              - http://immich.default.svc.cluster.local.:2283/api
              - $API_KEY
            envFrom:
              - secretRef:
                  name: immich-sync-secret
            probes:
              liveness: &probes
                enabled: false
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 150Mi
              limits:
                memory: 2Gi
    service:
      app:
        controller: *app
        enabled: false
    persistence:
      external:
        enabled: true
        type: nfs
        server: 192.168.9.10
        path: /mnt/vol1/photo/Export
        globalMounts:
          - path: /external_libs
