---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cleanuparr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cleanuparr-secret
    template:
      data:
        RADARR__INSTANCES__0__APIKEY: "{{ .RADARR__API_KEY }}"
        SONARR__INSTANCES__0__APIKEY: "{{ .SONARR__API_KEY }}"
  dataFrom:
    - extract:
        key: radarr
    - extract:
        key: sonarr
