---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kguardian
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kguardian-secret
    template:
      data:
        api-key: "{{ .LITELLM_MASTER_KEY }}"
  dataFrom:
    - extract:
        key: litellm
