---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/policy/poddisruptionbudget_v1.json
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: external-secrets-webhook
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: external-secrets
      app.kubernetes.io/name: external-secrets-webhook
