---
apiVersion: batch/v1
kind: Job
metadata:
  name: "wipe-${app}-${ts}"
  namespace: "${ns}"
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      containers:
        - name: wipe
          image: ghcr.io/home-operations/busybox:1.38.0@sha256:7e2c04dd50ede647bf4a7a4c8dbd629dd4971cd139b9b88fb22bfc3c7a6c13df
          command: ["/bin/sh", "-c", "cd /config; find . -delete"]
          volumeMounts:
            - name: config
              mountPath: /config
          securityContext:
            privileged: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: "${claim}"
