---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: litellm-operator
spec:
  chartRef:
    kind: OCIRepository
    name: litellm-operator
  interval: 30m
  values:
    controller:
      leaderElection:
        enabled: true
    webhook:
      enabled: true
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 512Mi
