host: "https://docs.xpander.ovh"
formats:
  - markdown
  - pdf
assets:
  export_images: true
  export_attachments: true
  modify_links: false
  export_meta: false
keep_last: 5
notifications:
  apprise:
    on_success: false
    on_failure: true
